<a href="https://colab.research.google.com/github/tutsilianna/Introduction_to_ML_and_Advanced_ML_Python/blob/main/Exam/trial_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 3

In [103]:
import pandas as pd

data = pd.read_csv('/content/asset-v1_ITMOUniversity+INTROMLADVML+fall_2023_ITMO_mag+type@asset+block@pulsar_stars_new.csv')

data.head()

MIP      STDIP      EKIP       SIP        MC       STDC        EKC  \
0  140.562500  55.683782 -0.234571 -0.699648  3.199833  19.110426   7.975532   
1  102.507812  58.882430  0.465318 -0.515088  1.677258  14.860146  10.576487   
2  103.015625  39.341649  0.323328  1.051164  3.121237  21.744669   7.735822   
3  136.750000  57.178449 -0.068415 -0.636238  3.642977  20.959280   6.896499   
4   88.726562  40.672225  0.600866  1.123492  1.178930  11.468720  14.269573   

           SC  TG  
0   74.242225   0  
1  127.393580   0  
2   63.171909   0  
3   53.593661   0  
4  252.567306   0

**Prepare the data for training the algorithms:**

1. Form a sample for further work as follows: select only those objects that have `MIP` ∈ [10, 100]

Enter the number of rows in the resulting sample:

In [104]:
data1 = data.loc[(data['MIP'] <= 100) & (data['MIP']>=10)]
data1.shape

(4218, 9)

Determine the sample mean for the column `MIP`:

In [105]:
round(data1['MIP'].mean(), 3)

77.053

Determine the minimum value from the column `MIP`:

In [106]:
round(data1['MIP'].min(), 3)

10.008

2. Sort the data in the `SIP` column in ascending order, and then split the dataset into training and test samples using `train_test_split()` in the ratio `80:20` with the parameter `random_state = 33`. Use stratification by the target feature.

Determine the maximal value of the column `STDC` from the training sample:

In [107]:
data2 = data1.sort_values(by='SIP', ignore_index=True, ascending = True)
data2.head()

MIP      STDIP      EKIP       SIP          MC       STDC       EKC  \
0  92.804688  73.323775  0.470206 -1.040048   21.126254  40.828972  1.837012   
1  84.132812  74.457556  0.694280 -0.965077   98.496656  50.698540  1.170048   
2  96.070312  74.560083  0.703671 -0.960082   10.634615  35.096062  3.711222   
3  74.632812  75.867161  0.834880 -0.838742   67.623746  81.199889  0.998825   
4  99.281250  71.956469  0.765558 -0.827640  197.234114  63.758798 -1.876388   

          SC  TG  
0   2.433000   0  
1   0.858232   0  
2  14.282259   1  
3  -0.311267   0  
4   2.431297   0

In [108]:
from sklearn.model_selection import train_test_split

y = data2['TG']
data2.drop(axis=1, columns=['TG'], inplace=True)
X = data2
X.head()

MIP      STDIP      EKIP       SIP          MC       STDC       EKC  \
0  92.804688  73.323775  0.470206 -1.040048   21.126254  40.828972  1.837012   
1  84.132812  74.457556  0.694280 -0.965077   98.496656  50.698540  1.170048   
2  96.070312  74.560083  0.703671 -0.960082   10.634615  35.096062  3.711222   
3  74.632812  75.867161  0.834880 -0.838742   67.623746  81.199889  0.998825   
4  99.281250  71.956469  0.765558 -0.827640  197.234114  63.758798 -1.876388   

          SC  
0   2.433000  
1   0.858232  
2  14.282259  
3  -0.311267  
4   2.431297

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=33, stratify=y)

round(X_train['STDC'].max(), 3)

109.655

3. Perform the linear normalization transformation for the training dataset and apply it to the test data.

Determine the sample mean for column `STDIP` from the training sample (after normalization):

In [117]:
from sklearn.preprocessing import MinMaxScaler
scaler1 = MinMaxScaler().fit(X_train)

x_train = pd.DataFrame(scaler1.transform(X_train), columns = X_train.columns)
x_test =  pd.DataFrame(scaler1.transform(X_test), columns = X_test.columns)

round(x_train['STDIP'].mean(), 3)

0.255

**Use the data obtained and train models**

Train the `LogisticRegression()` model on training dataset using all default parameters. Evaluate the model on test dataset.

Make a confusion matrix. Enter a value for True Positive (TP):

In [118]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

log_reg = LogisticRegression().fit(x_train, y_train)

y_pred = log_reg.predict(x_test)
confusion_matrix(y_test, y_pred)

array([[671,  25],
       [ 50, 309]])

In [112]:
import numpy as np

TP = np.diag(confusion_matrix(y_test, y_pred))
TP

array([671, 309])

Compute `f1 score` for the test dataset.

In [113]:
from sklearn.metrics import f1_score

round(f1_score(y_test, y_pred), 3)

0.892

Train the `KNeighborsClassifier(n_neighbors=3)` model on training dataset using all default parameters. Evaluate the model on test dataset.

Make a confusion matrix. Enter a value for True Positive (TP):

In [114]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3).fit(x_train, y_train)

y_pred_knn = knn.predict(x_test)
confusion_matrix(y_test, y_pred_knn)

array([[671,  25],
       [ 33, 326]])

In [115]:
TP = np.diag(confusion_matrix(y_test, y_pred_knn))
TP

array([671, 326])

Compute `f1 score` for the test dataset.

In [116]:
round(f1_score(y_test, y_pred_knn), 3)

0.918

# Task 4

[The provided dataset](https://drive.google.com/file/d/1_sYAHWRBnZe5hftLGJWlEjW0xB4EUeEt/view?usp=sharing) contains information on 60000 handwritten numeral writing patterns and class labels for training. [The following dataset](https://drive.google.com/file/d/1nwOCmnIx1eT-U-Vs9z2bsfj9G1olv7f6/view?usp=sharing) contains 10,000 samples and labels for testing. Each row consists of 785 values: the first value (label column) is the label (number from 0 to 9), and the remaining 784 values are pixel values (numbers from 0 to 255). [The data is also available on kaggle.](https://www.kaggle.com/datasets/oddrationale/mnist-in-csv)

1. Data preparation

a) From the training and test datasets, select images belonging to class 0 and 1.

b) Use the principal component analysis `PCA()` with the parameter `svd_solver='full'` to reduce the dimensionality of the resulting datasets. Determine the minimum number of principal components  to use so that the explained variance ratio exceeds `0.9` (is strictly greater than the specified value) on the training dataset.

Enter the number of principal components `M`:

c) Find the scores that meet the found `M` principal components for the training and test datasets.

Enter the coordinate relative to 1st principal component for 1st image in the training dataset:

2. Model training

Use the data (two classes and reduced dimensionality) to train the models below.

Train `sklearn.ensemble.GradientBoostingClassifier` model on test dataset with the following parameters: `n_estimators=500, learning_rate=0.8, random_state=23, max_depth=2`.

Build `classification_report` and the confusion matrix for the resulting model on test dataset.

Enter the model accuracy value:

Make an confusion matrix. Determine tp: